### ISSUE TITLE
Validação de nome de dispositivo repetido

### ISSUE THREAD

**Issue by DankoCaboski** [DankoCaboski/TIA-Portal-RPA#11]
Validar a não existencia de nomes de dispositivos repetidos antes de chamar o service que cria o hardware
Segestão: criar no banco uma tabela com o tipo do dispositivo e nome

**Comment by Gbrribeiro30** [comment]
Foi realizada a atividade, na tentativa de criar um device com o mesmo nome exibe um pop-up 




![Image](https://github.com/DankoCaboski/TIA-Portal-RPA/assets/133721315/acc9ae4a-a390-48de-96bc-baf8c37c0c5a)
